all:
	rm -f *appendix*.pdf
	pdflatex *appendix*.tex
	pdflatex *appendix*.tex
	evince *appendix*.pdf &
clean:
	rm -rf *.log
	rm -rf *.toc
	rm -rf *.bbl
	rm -rf *.aux
	rm -rf *.blg
	rm -rf *.spl
	rm -rf *.out
	rm -rf *.zip

